global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s
  
scrape_configs:
  - job_name: prometheus
    scrape_interval: 60s
    scrape_timeout: 15s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - mongodbatlas-exporter:9905
