{
 "title": "Mongodb Atlas",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(mongodbatlas_processes_stats_connections, user_alias)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_system_cpu_user_percent{user_alias=~\"${cluster}-.*\"}",
     "legendFormat": "{{ user_alias }} user"
    },
    {
     "expr": "mongodbatlas_processes_stats_system_cpu_iowait_percent",
     "legendFormat": "{{ user_alias }} io_wait"
    }
   ]
  },
  {
   "title": "System memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_system_memory_used_bytes{user_alias=~\"$cluster.*\"}",
     "legendFormat": "{{ user_alias }}"
    }
   ]
  },
  {
   "title": "Data disk write latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_disks_stats_disk_partition_latency_write_seconds{partition_name=\"data\",user_alias=~\"${cluster}-.*\"}",
     "legendFormat": "{{ user_alias }}"
    }
   ]
  },
  {
   "title": "Data disk read latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_disks_stats_disk_partition_latency_read_seconds{partition_name=\"data\",user_alias=~\"${cluster}-.*\"}",
     "legendFormat": "{{ user_alias }}"
    }
   ]
  }
 ]
}