{
 "title": "MongoDB metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(mongodbatlas_processes_stats_connections, user_alias)"
    }
   },
   {
    "name": "processType",
    "label": "processType",
    "query": {
     "query": "label_values(mongodbatlas_processes_stats_info, type)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,5m,15m,30m,1h,2h,1d"
   },
   {
    "name": "projectId",
    "label": "projectId",
    "query": {
     "query": "label_values(mongodbatlas_processes_stats_info, project_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Assert Events ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_assert_msg_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "{{ user_alias }} msg"
    },
    {
     "expr": "mongodbatlas_processes_stats_assert_regular_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "{{ user_alias }} regular"
    },
    {
     "expr": "mongodbatlas_processes_stats_assert_user_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "{{ user_alias }} user"
    },
    {
     "expr": "mongodbatlas_processes_stats_assert_warning_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "{{ user_alias }} warning"
    }
   ]
  },
  {
   "title": "Operations counter ratio",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_opcounter_cmd_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "{{ user_alias }} cmd"
    },
    {
     "expr": "mongodbatlas_processes_stats_opcounter_delete_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "{{ user_alias }} delete"
    },
    {
     "expr": "mongodbatlas_processes_stats_opcounter_getmore_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "{{ user_alias }} getmore"
    },
    {
     "expr": "mongodbatlas_processes_stats_opcounter_insert_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "{{ user_alias }} insert"
    },
    {
     "expr": "mongodbatlas_processes_stats_opcounter_query_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "{{ user_alias }} query"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_connections{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "{{ user_alias }} cmd"
    }
   ]
  },
  {
   "title": "Cursor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_cursors_total_open{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "{{ user_alias }} total open"
    },
    {
     "expr": "mongodbatlas_processes_stats_cursors_total_timed_out_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "{{ user_alias }} total open"
    }
   ]
  },
  {
   "title": "Document operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_document_metrics_deleted_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "{{ user_alias }} deleted"
    },
    {
     "expr": "mongodbatlas_processes_stats_document_metrics_inserted_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "{{ user_alias }} inserted"
    },
    {
     "expr": "mongodbatlas_processes_stats_document_metrics_returned_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "{{ user_alias }} returned"
    },
    {
     "expr": "mongodbatlas_processes_stats_document_metrics_updated_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "{{ user_alias }} updated"
    }
   ]
  },
  {
   "title": "Queued operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_global_lock_current_queue_readers{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "reader {{ user_alias }}"
    },
    {
     "expr": "mongodbatlas_processes_stats_global_lock_current_queue_writers{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "writer {{ user_alias }}"
    }
   ]
  },
  {
   "title": "Query executor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_query_executor_scanned_objects_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"} ",
     "legendFormat": "reader {{ user_alias }}"
    },
    {
     "expr": "mongodbatlas_processes_stats_query_executor_scanned_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "writer {{ user_alias }}"
    }
   ]
  },
  {
   "title": "Query targetting",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_query_targeting_scanned_objects_per_returned{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"} ",
     "legendFormat": "scanned obj/return {{ user_alias }}"
    },
    {
     "expr": "mongodbatlas_processes_stats_query_targeting_scanned_per_returned{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "scanned/return {{ user_alias }}"
    }
   ]
  },
  {
   "title": "Query targetting",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_operations_scan_and_order_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"} ",
     "legendFormat": "{{ user_alias }} scan and order"
    }
   ]
  },
  {
   "title": "Page faults",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_extra_info_page_faults_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"} ",
     "legendFormat": "{{ user_alias }} scan and order"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_cache_bytes_read_into_bytes_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"} ",
     "legendFormat": "Read into {{ user_alias }}"
    },
    {
     "expr": "mongodbatlas_processes_stats_cache_bytes_written_from_bytes_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "Written from {{ user_alias }}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_cache_used_bytes_bytes{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"} ",
     "legendFormat": "Read into {{ user_alias }}"
    },
    {
     "expr": "mongodbatlas_processes_stats_cache_bytes_written_from_bytes_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "Written from {{ user_alias }}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache dirty",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_cache_dirty_bytes_bytes{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"} ",
     "legendFormat": "Read into {{ user_alias }}"
    },
    {
     "expr": "mongodbatlas_processes_stats_cache_bytes_written_from_bytes_ratio{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "Written from {{ user_alias }}"
    }
   ]
  },
  {
   "title": "WiredTiger Concurrency Tickets Available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_tickets_available_reads{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"} ",
     "legendFormat": "Read {{ user_alias }}"
    },
    {
     "expr": "mongodbatlas_processes_stats_tickets_available_write{user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\", project_id=~\"$projectId\"}",
     "legendFormat": "write{{ user_alias }}"
    }
   ]
  }
 ]
}