{
 "title": "System/disks metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(mongodbatlas_processes_stats_connections, user_alias)"
    }
   },
   {
    "name": "processType",
    "label": "processType",
    "query": {
     "query": "label_values(mongodbatlas_processes_stats_info, type)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,5m,15m,30m,1h,2h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Data disk read latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_disks_stats_disk_partition_latency_read_seconds{partition_name=\"data\",user_alias=~\"${cluster}-.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\"}",
     "legendFormat": "{{ user_alias }}"
    }
   ]
  },
  {
   "title": "Data disk write latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_disks_stats_disk_partition_latency_write_seconds{partition_name=\"data\",user_alias=~\"${cluster}-.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\"}",
     "legendFormat": "{{ user_alias }}"
    }
   ]
  },
  {
   "title": "DISK IOPS read ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_disks_stats_disk_partition_iops_read_ratio{partition_name=\"data\",user_alias=~\"${cluster}-.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\"}",
     "legendFormat": "{{ user_alias }}"
    }
   ]
  },
  {
   "title": "DISK IOPS write ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_disks_stats_disk_partition_iops_write_ratio{partition_name=\"data\",user_alias=~\"${cluster}-.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\"}",
     "legendFormat": "{{ user_alias }}"
    }
   ]
  },
  {
   "title": "DISK space percent free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_disks_stats_disk_partition_space_percent_free_percent{partition_name=\"data\",user_alias=~\"${cluster}.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\"}",
     "legendFormat": "{{ user_alias }}"
    }
   ]
  },
  {
   "title": "DISK space percent used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_disks_stats_disk_partition_space_percent_used_percent{partition_name=\"data\",user_alias=~\"${cluster}-.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\"}",
     "legendFormat": "{{ user_alias }}"
    }
   ]
  },
  {
   "title": "Normalized process CPU user/kernel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_process_normalized_cpu_user_percent{user_alias=~\"${cluster}-.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\"}",
     "legendFormat": "{{ user_alias }} user"
    },
    {
     "expr": "mongodbatlas_processes_stats_process_normalized_cpu_kernel_percent{user_alias=~\"${cluster}-.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\"}",
     "legendFormat": "{{ user_alias }} kernel"
    }
   ]
  },
  {
   "title": "Normalized System CPU user/iowait",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_system_normalized_cpu_user_percent{user_alias=~\"${cluster}-.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\"}",
     "legendFormat": "{{ user_alias }} user"
    },
    {
     "expr": "mongodbatlas_processes_stats_system_normalized_cpu_iowait_percent{user_alias=~\"${cluster}-.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\"}",
     "legendFormat": "{{ user_alias }} kernel"
    }
   ]
  },
  {
   "title": "Swap percent usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_swap_usage_used_bytes{user_alias=~\"${cluster}-.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\"} / (\nmongodbatlas_processes_stats_swap_usage_free_bytes{user_alias=~\"${cluster}-.*\"} + mongodbatlas_processes_stats_swap_usage_used_bytes{user_alias=~\"${cluster}-.*\"} ) * 100",
     "legendFormat": "{{ user_alias }}"
    }
   ]
  },
  {
   "title": "System memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mongodbatlas_processes_stats_system_memory_used_bytes{user_alias=~\"${cluster}-.*\"} * on (user_alias) group_left mongodbatlas_processes_stats_info{type=~\"$processType\"}",
     "legendFormat": "{{ user_alias }} used"
    }
   ]
  }
 ]
}