name: release
on: 
  release:
    types: [created]

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
    - name: Checkout code
      uses: actions/checkout@v1
    - name: build
      run: make build
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/mongodbatlas_exporter
        asset_name: mongodbatlas_exporter
        tag: ${{ github.ref }}
        overwrite: true
