name: release
on: 
  release:
    types: [created]

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
    - name: build
      run: make build
    - name: Upload files
      uses: AButler/upload-release-assets@v2.0
      with:
        files: '/bin/mongodbatlas_exporter'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
